language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  - sudo python3 manage.py migrate
  - sudo python3 manage.py makemigrations
  - sudo python3 manage.py test
