language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  - python3 manage.py migrate
  - python3 manage.py makemigrations
  - python3 manage.py test
  # just a test :-)
  - coverage run manage.py test
after_success:
  - codecov
